name: Deploy To Production
on:
  workflow_dispatch:
    inputs:
      DeployTo:
        description: 'Deploy To'
        default: 'ALL'
        type: choice
        options:
        - ALL
        - PGN-MOBILE
        - RELYON

jobs:
  set_target_env:
    name: Define Environment
    runs-on: ubuntu-latest
    steps:
      - name: print
        run: |
          getBranchName=${{ github.event_name == 'pull_request' && github.base_ref || github.event_name == 'workflow_dispatch' &&  github.ref_name}}   
          
          echo "${{ inputs.DeployTo }} $getBranchName"
